I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script
    mc "Holy crap! I killed the Chieftain! I won!"
IOError: Couldn't find file 'heartAttackFall.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script
    mc "Holy crap! I killed the Chieftain! I won!"
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/ast.py", line 678, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/exports.py", line 1229, in say
    who(what, *args, **kwargs)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/character.py", line 1031, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/character.py", line 823, in do_display
    **display_args)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/character.py", line 572, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/ui.py", line 289, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/display/core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/display/core.py", line 3096, in interact_core
    renpy.audio.audio.interact()
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/audio/audio.py", line 1062, in interact
    periodic()
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/audio/audio.py", line 993, in periodic_thread_main
    periodic_pass()
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/audio/audio.py", line 937, in periodic_pass
    c.periodic()
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/audio/audio.py", line 419, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/audio/audio.py", line 71, in load
    rv = renpy.loader.load(fn)
  File "/home/kyle/Downloads/renpy-7.1.3-sdk/renpy/loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'heartAttackFall.mp3'.

Linux-4.19.4-1-default-x86_64-with-glibc2.2.5
Ren'Py 7.1.3.1092
Chad Island 1.0
Mon Dec  3 19:27:20 2018
